eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

# 开启hystrix熔断功能
feign:
  hystrix:
    enabled: true